# A local development project.
# Refer to the docs for more details: https://supabase.com/docs/reference/cli/supabase-init
[project]
project_id = "your-project-id"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 9999
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54322
shadow_port = 54320
major_version = 15

[functions.delete-user]
enabled = true
verify_jwt = true
import_map = "./functions/delete-user/deno.json"
entrypoint = "./functions/delete-user/index.ts"

[functions.create-user]
enabled = true
verify_jwt = true
import_map = "./functions/create-user/deno.json"
entrypoint = "./functions/create-user/index.ts"

[storage]
enabled = true
port = 54323
file_size_limit = "50MiB"

[edge-runtime]
enabled = true
port = 54324

[analytics]
enabled = false
port = 54327
vector_port = 54328
